use crate::commands::mods::ProjectMod;
use std::fs;
use std::path::Path;

pub fn export_zip_pack(
    project_name: &str,
    _mc_version: &str,
    _loader: &str,
    mods: &[ProjectMod],
    output_path: &str,
) -> Result<String, String> {
    let pack_dir = Path::new(output_path).join(project_name);
    let mods_dir = pack_dir.join("mods");
    fs::create_dir_all(&mods_dir).map_err(|e: std::io::Error| e.to_string())?;

    let readme = format!(
        "# {}\n\nGenerated by ModCanvas\n\n## Mods ({}):\n\n{}",
        project_name,
        mods.len(),
        mods.iter()
            .map(|m| format!("- {} ({})", m.name, m.version_number.as_deref().unwrap_or("unknown")))
            .collect::<Vec<_>>()
            .join("\n")
    );
    fs::write(pack_dir.join("README.md"), readme).map_err(|e: std::io::Error| e.to_string())?;

    Ok(pack_dir.to_string_lossy().to_string())
}
